- 
  version: 0.7.3.1.{build}
  branches:
    only:
    - master
  skip_tags: true

  os: Visual Studio 2015
  configuration: Release

  clone_depth: 1

  clone_folder: C:\_Repos\LunaLUA

  build:
    project: LunaDll.sln
    verbosity: minimal

  after_build:
  - cmd: deploy-full.bat nopause

  artifacts:
  - path: LunaLUA-bin.zip
  - path: LunaLoader-bin.zip
  - path: Release\LunaDLL.dll

  deploy:
  - provider: Environment
    name: WohlnetFTP

- 
  version: 0.7.3.1.{build}
  branches:
    only:
    - cleanup
  skip_tags: true
  
  os: Visual Studio 2017
  
  clone_depth: 1
  clone_folder: C:\_Repos\LunaLUA
  
  build_script:
  - cmd: where git
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: mkdir build-appveyor-vs2017
  - cmd: cd build-appveyor-vs2017
  - cmd: cmake ../. -G "Visual Studio 15 2017" -DGIT_EXECUTABLE="C:\Program Files\Git\bin\git.exe"
  - cmd: cmake --build . --config release
