-
  version: 0.7.3.1.{build}
  branches:
    only:
    - master
  skip_tags: true

  os: Visual Studio 2015
  configuration: Release

  clone_depth: 1

  clone_folder: C:\_Repos\LunaLUA

  install:
  - cmd: git submodule init
  - cmd: git submodule update

  build:
    project: LunaDll.sln
    verbosity: minimal

  after_build:
  - cmd: build-lunaexec.bat
  - cmd: deploy-full.bat nopause

  artifacts:
  - path: LunaLUA-bin.zip
  - path: LunaLoader-bin.zip
  - path: Release\LunaDLL.dll
  - path: LunaLoader-exec.7z

  deploy:
  - provider: Environment
    name: WohlnetFTP

-
  version: 0.7.3.1.{build}
  branches:
    only:
    - master
  skip_tags: true

  os: Visual Studio 2017
  configuration: Release

  clone_depth: 1

  clone_folder: C:\_Repos\LunaLUA

  install:
  - cmd: git submodule init
  - cmd: git submodule update

  build:
  - cmd: build_launcher_2017.bat

  after_build:
  - cmd: deploy-full.bat nopause

  artifacts:
  - path: SMBX-Launcher.zip

  deploy:
  - provider: Environment
    name: WohlnetFTP

-
  version: 0.7.3.1.{build}
  branches:
    only:
    - cleanup
  skip_tags: true

  os: Visual Studio 2017

  clone_depth: 1
  clone_folder: C:\_Repos\LunaLUA

  install:
  - cmd: git submodule init
  - cmd: git submodule update

  build_script:
  - cmd: mkdir build-appveyor-vs2017
  - cmd: cd build-appveyor-vs2017
  - cmd: cmake ../. -G "Visual Studio 15 2017"
  - cmd: cmake --build . --config release
